/**
 * Created by quipoo on 2019/2/11.
 */
export const LOGIN 	= 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const SET_DISCOVER_DATA = 'SET_DISCOVER_DATA';
export const UPDATE_NOTICES_TIP = 'UPDATE_NOTICES_TIP'
export const MODAL_VISIBLE = 'MODAL_VISIBLE'
export const UPDATE_FAMILY_MEMBER = 'UPDATE_FAMILY_MEMBER'
export const START_FETCH_FAMILY_MEMBER = 'START_FETCH_FAMILY_MEMBER'
export const END_FETCH_FAMILY_MEMBER = 'END_FETCH_FAMILY_MEMBER'